# Generated by Django 5.1.1 on 2024-09-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_id',
        ),
    ]
