# Generated by Django 5.1.1 on 2024-09-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_inventory_product_inventory_quantity_and_more'),
        ('home', '0003_remove_product_cart_id'),
    ]

    operations = [
    ]
