# Generated by Django 5.1.1 on 2024-09-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
