# Generated by Django 5.1.1 on 2024-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
